# Generated by Django 3.2.9 on 2021-12-03 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_rename_demoapp_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
